"""empty message

Revision ID: 91faa61f10fe
Revises: 
Create Date: 2025-05-03 05:10:25.460596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91faa61f10fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_ts')

    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_constraint('bids_tender_id_vendor_id_key', type_='unique')
        batch_op.drop_index('idx_bids_tender')
        batch_op.create_unique_constraint('_tender_vendor_uc', ['tender_id', 'vendor_id'])

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index('idx_scores_bid')
        batch_op.drop_constraint('scores_bid_id_criterion_id_evaluator_id_key', type_='unique')
        batch_op.create_unique_constraint('_score_uc', ['bid_id', 'criterion_id', 'evaluator_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_vendor', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vendor_companies', ['vendor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_user_vendor', 'vendor_companies', ['vendor_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint('_score_uc', type_='unique')
        batch_op.create_unique_constraint('scores_bid_id_criterion_id_evaluator_id_key', ['bid_id', 'criterion_id', 'evaluator_id'])
        batch_op.create_index('idx_scores_bid', ['bid_id'], unique=False)

    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_constraint('_tender_vendor_uc', type_='unique')
        batch_op.create_index('idx_bids_tender', ['tender_id'], unique=False)
        batch_op.create_unique_constraint('bids_tender_id_vendor_id_key', ['tender_id', 'vendor_id'])

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_audit_ts', [sa.text('ts DESC')], unique=False)

    # ### end Alembic commands ###
